name: terminal
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16'
          java-package: jdk
          architecture: x64
      - run: java -jar junit.jar -cp . --scan-classpath
      - run: javac -cp .:junit.jar *.java
      - run: javadoc -d out -cp junit.jar *.java
